chore: cleanup taskfile
Signed-off-by: Joel Van Eenwyk <joel.vaneenwyk@gmail.com>

diff --git a/taskfile.yaml b/taskfile.yaml
--- a/taskfile.yaml
+++ b/taskfile.yaml
@@ -4,303 +4,313 @@
 version: "3"
 
 vars:
-  VCPKG_BOOTSTRAP_BAT: "{{.TASKFILE_DIR}}/build-aux/vcpkg/bootstrap-vcpkg.bat"
-  VCPKG_BOOTSTRAP_SH: "{{.TASKFILE_DIR}}/build-aux/vcpkg/bootstrap-vcpkg.sh"
-  VCPKG_EXE: "{{.TASKFILE_DIR}}/build-aux/vcpkg/vcpkg.exe"
+    VCPKG_BOOTSTRAP_BAT: "{{.TASKFILE_DIR}}/build-aux/vcpkg/bootstrap-vcpkg.bat"
+    VCPKG_BOOTSTRAP_SH: "{{.TASKFILE_DIR}}/build-aux/vcpkg/bootstrap-vcpkg.sh"
+    VCPKG_EXE: "{{.TASKFILE_DIR}}/build-aux/vcpkg/vcpkg.exe"
 
-  RUN_WINDOWS: 'cmd /d /c'
-  RUN_UNIX: 'sh -c'
-  RUN: '{{if eq OS "windows"}}{{.RUN_WINDOWS}}{{ else }}{{.RUN_UNIX}}{{ end }}'
+    RUN_WINDOWS: "cmd /d /c"
+    RUN_UNIX: "sh -c"
+    RUN: '{{if eq OS "windows"}}{{.RUN_WINDOWS}}{{ else }}{{.RUN_UNIX}}{{ end }}'
 
-  MSBUILD_EXE_RAW:
-    sh: |
-      strings=("Preview" "Enterprise" "Professional" "Community")
-      for str in "${strings[@]}"
-      do
-        result="C:/Program Files/Microsoft Visual Studio/2022/${str}/MSBuild/Current/Bin/amd64/MSBuild.exe"
-        if [ -e "$result" ]; then
-          echo "$result"
-          break
-        fi
-      done
-  MSBUILD_EXE: '{{fromSlash .MSBUILD_EXE_RAW}}'
+    MSBUILD_EXE_RAW:
+        sh: |
+            strings=("Preview" "Enterprise" "Professional" "Community")
+            for str in "${strings[@]}"
+            do
+              result="C:/Program Files/Microsoft Visual Studio/2022/${str}/MSBuild/Current/Bin/amd64/MSBuild.exe"
+              if [ -e "$result" ]; then
+                echo "$result"
+                break
+              fi
+            done
+    MSBUILD_EXE: "{{fromSlash .MSBUILD_EXE_RAW}}"
+    BUILD_INT_BASE_DIR: "{{.TASKFILE_DIR}}/.build"
+    BUILD_INT_DIR: "{{.BUILD_INT_BASE_DIR}}/vscode"
+    BUILD_DIR: "{{fromSlash .BUILD_INT_DIR}}"
 
-  BUILD_INT_BASE_DIR: "{{.TASKFILE_DIR}}/.build"
-  BUILD_INT_DIR: "{{.BUILD_INT_BASE_DIR}}/vscode"
-  BUILD_DIR: "{{fromSlash .BUILD_INT_DIR}}"
-
-  BUILD_TOOLCHAIN:
-  BUILD_ARCH: x86_64
-  BUILD_CC: clang
-  PACKAGE_PARTS:
-    - "mingw-w64"
-    - "{{.BUILD_TOOLCHAIN}}"
-    - "{{.BUILD_ARCH}}"
-  PACKAGE_NAME_PREFIX: '{{ without .PACKAGE_PARTS "" | join "-" }}'
-  MSYS2_PACKAGES:
-    - "git"
-    - "ncurses"
-    - "{{.PACKAGE_NAME_PREFIX}}-{{.BUILD_CC}}"
-    - "{{.PACKAGE_NAME_PREFIX}}-clang"
-    # - "{{.PACKAGE_NAME_PREFIX}}-gcc"
-    # - "{{.PACKAGE_NAME_PREFIX}}-glib2"
-    # - "{{.PACKAGE_NAME_PREFIX}}-meson"
-    - "{{.PACKAGE_NAME_PREFIX}}-ncurses"
-    - "{{.PACKAGE_NAME_PREFIX}}-ntldd"
-    - "{{.PACKAGE_NAME_PREFIX}}-openssl"
-    - "{{.PACKAGE_NAME_PREFIX}}-pkgconf"
-    - "{{.PACKAGE_NAME_PREFIX}}-zlib"
-    # Defaults
-    - "{{.PACKAGE_NAME_PREFIX}}-gstreamer"
-    - "{{.PACKAGE_NAME_PREFIX}}-pango"
-    - "{{.PACKAGE_NAME_PREFIX}}-gcc"
-    - "{{.PACKAGE_NAME_PREFIX}}-binutils"
-    - "{{.PACKAGE_NAME_PREFIX}}-cairo"
-    - "{{.PACKAGE_NAME_PREFIX}}-gdk-pixbuf2"
-    - "{{.PACKAGE_NAME_PREFIX}}-glib2"
-    - "{{.PACKAGE_NAME_PREFIX}}-libepoxy"
-    - "{{.PACKAGE_NAME_PREFIX}}-pango"
-    - "{{.PACKAGE_NAME_PREFIX}}-cairo"
-  MSYS2_PYTHON_PACKAGES:
-    - "{{.PACKAGE_NAME_PREFIX}}-python"
-    - "{{.PACKAGE_NAME_PREFIX}}-python-pip"
-    - "{{.PACKAGE_NAME_PREFIX}}-python-pkgconfig"
+    BUILD_TOOLCHAIN:
+    BUILD_ARCH: x86_64
+    BUILD_CC: clang
+    PACKAGE_PARTS:
+        - "mingw-w64"
+        - "{{.BUILD_TOOLCHAIN}}"
+        - "{{.BUILD_ARCH}}"
+    PACKAGE_NAME_PREFIX: '{{ without .PACKAGE_PARTS "" | join "-" }}'
+    MSYS2_PACKAGES:
+        - "git"
+        - "ncurses"
+        - "{{.PACKAGE_NAME_PREFIX}}-{{.BUILD_CC}}"
+        - "{{.PACKAGE_NAME_PREFIX}}-clang"
+        # - "{{.PACKAGE_NAME_PREFIX}}-gcc"
+        # - "{{.PACKAGE_NAME_PREFIX}}-glib2"
+        # - "{{.PACKAGE_NAME_PREFIX}}-meson"
+        - "{{.PACKAGE_NAME_PREFIX}}-ncurses"
+        - "{{.PACKAGE_NAME_PREFIX}}-ntldd"
+        - "{{.PACKAGE_NAME_PREFIX}}-openssl"
+        - "{{.PACKAGE_NAME_PREFIX}}-pkgconf"
+        - "{{.PACKAGE_NAME_PREFIX}}-zlib"
+        # Defaults
+        - "{{.PACKAGE_NAME_PREFIX}}-gstreamer"
+        - "{{.PACKAGE_NAME_PREFIX}}-pango"
+        - "{{.PACKAGE_NAME_PREFIX}}-gcc"
+        - "{{.PACKAGE_NAME_PREFIX}}-binutils"
+        - "{{.PACKAGE_NAME_PREFIX}}-cairo"
+        - "{{.PACKAGE_NAME_PREFIX}}-gdk-pixbuf2"
+        - "{{.PACKAGE_NAME_PREFIX}}-glib2"
+        - "{{.PACKAGE_NAME_PREFIX}}-libepoxy"
+        - "{{.PACKAGE_NAME_PREFIX}}-pango"
+        - "{{.PACKAGE_NAME_PREFIX}}-cairo"
+    MSYS2_PYTHON_PACKAGES:
+        - "{{.PACKAGE_NAME_PREFIX}}-python"
+        - "{{.PACKAGE_NAME_PREFIX}}-python-pip"
+        - "{{.PACKAGE_NAME_PREFIX}}-python-pkgconfig"
+    TARGET: x86_64-pc-windows-gnu
 
 env:
-  VCPKG_DISABLE_METRICS: 1
+    VCPKG_DISABLE_METRICS: 1
 
 tasks:
-  default:
-    cmds:
-      - task: build
+    default:
+        cmds:
+            - task: build
 
-  build:
-    cmds:
-      - cmd: |
-          TARGET=x86_64-pc-windows-gnu
-          export PKG_CONFIG_PATH="/usr/lib64/pkgconfig:/usr/share/pkgconfig:$MINGW_PREFIX/lib/pkgconfig/:/usr/x86_64-w64-mingw32/lib/pkgconfig/:$PKG_CONFIG_PATH"
-          export PKG_CONFIG_SYSROOT_DIR="$MINGW_PREFIX"
-          cargo build --target="$TARGET" --release --locked
-          mkdir -p package
-          cp "target/$TARGET/release/czkawka_gui.exe" package/
-          cp "target/$TARGET/release/czkawka_cli.exe" package/
+    build:
+        deps: [gtk4]
+        cmds:
+            - cmd: |
+                  export PKG_CONFIG_PATH="{{.TASKFILE_DIR}}/.build/gtk4/gtk/x64/release/lib/pkgconfig:$PKG_CONFIG_PATH"
+                  cargo build --release --locked
+            - cmd: |
+                  mkdir package || true
+                  cp "target/{{.TARGET}}/release/czkawka_gui.exe" package/ || true
+                  cp "target/{{.TARGET}}/release/czkawka_cli.exe" package/ || true
 
-  gtk4:
-    cmds:
-      - cmd: |
-          rye run gvsbuild \
-            build gtk4 \
-            --verbose \
-            --from-scratch \
-            --build-dir .build/gtk4 \
-            --msys-dir "$USERPROFILE/scoop/apps/msys2/current"
-      
-  czkawka-build:
-    deps: [install-dependencies]
-    cmds:
-      - cmd: rye sync --no-lock
-      - cmd: |
-          cmd.exe /D /C \
-            ""{{ joinPath .TASKFILE_DIR ".venv" "Scripts" "activate.bat" | shellQuote }}" && pixi run cargo build"
+    gtk4:
+        sources:
+            - uv.lock
+        generates:
+            - .build/gtk4/
+        cmds:
+            - cmd: |
+                  uv run gvsbuild \
+                    build gtk4 \
+                    --verbose \
+                    --build-dir .build/gtk4 \
+                    --msys-dir "$USERPROFILE/scoop/apps/msys2/current"
 
-  install-dependencies:
-    deps: [install-packages-scoop-pkg-config]
-    cmds:
-      - task: install-packages
-      - task: vcpkg-integrate
+    venv:
+        sources:
+            - pyproject.toml
+        generates:
+            - .venv/
+        cmds:
+            - cmd: uv sync
 
-  scoop-install:
-    desc: Install libraries with scoop
-    status:
-      - 'scoop --version'
-    cmds:
-      - cmd: pwsh -NoProfile -Command 'iex "& {$(irm get.scoop.sh)} -RunAsAdmin"'
+    czkawka-build:
+        deps: [install-dependencies, venv]
+        cmds:
+            - cmd: |
+                  cmd.exe /D /C \
+                    ""{{ joinPath .TASKFILE_DIR ".venv" "Scripts" "activate.bat" | shellQuote }}" && pixi run cargo build"
+
+    install-dependencies:
+        deps: [install-packages-scoop-pkg-config]
+        cmds:
+            - task: install-packages
+            - task: vcpkg-integrate
+
+    scoop-install:
+        desc: Install libraries with scoop
+        status:
+            - "scoop --version"
+        cmds:
+            - cmd: pwsh -NoProfile -Command 'iex "& {$(irm get.scoop.sh)} -RunAsAdmin"'
+              platforms: [windows]
+              ignore_error: true
+            - cmd: pwsh -NoProfile -Command 'Join-Path (Resolve-Path ~).Path "scoop/shims" >> $Env:GITHUB_PATH'
+              platforms: [windows]
+              ignore_error: true
+
+    git-submodule-init:
+        status:
+            - 'test -f "{{.VCPKG_BOOTSTRAP_BAT}}"'
+        cmds:
+            - cmd: 'git -C "{{.TASKFILE_DIR}}" submodule update --init --recursive'
+
+    vcpkg-integrate:
+        deps: [vcpkg-download]
+        internal: true
+        cmds:
+            - cmd: '{{.RUN}} "{{ fromSlash .VCPKG_EXE }}" integrate install'
+
+    vcpkg-download:
+        deps: [git-submodule-init]
+        status:
+            - 'test -f "{{.VCPKG_EXE}}"'
+        cmds:
+            - cmd: '{{.RUN}} "{{ fromSlash .VCPKG_BOOTSTRAP_BAT }}" -disableMetrics'
+
+    vcpkg:
+        deps: [vcpkg-download]
+        cmds:
+            - cmd: '{{.RUN}} "{{ fromSlash .VCPKG_EXE }}" {{.CLI_ARGS}}'
+
+    update-packages:
+        ignore_error: true
+        cmds:
+            - task: update-packages-pacman
+
+    update-packages-pacman:
+        deps: [pacman-unlock]
+        cmds:
+            - task: pacman-unlock
+            - cmd: "pacman -Syu --noconfirm"
+              ignore_error: true
+
+    install-packages:
+        cmds:
+            - task: install-packages-scoop-pkg-config
+            - task: install-packages-pacman
+
+    install-packages-scoop-pkg-config:
+        deps: [scoop-install]
         platforms: [windows]
-        ignore_error: true
-      - cmd: pwsh -NoProfile -Command 'Join-Path (Resolve-Path ~).Path "scoop/shims" >> $Env:GITHUB_PATH'
-        platforms: [windows]
-        ignore_error: true
+        status:
+            - pkg-config --version
+        cmds:
+            - cmd: |
+                  scoop install \
+                    extras/pkg-config-lite \
+                    main/winflexbison
 
-  git-submodule-init:
-    status:
-      - 'test -f "{{.VCPKG_BOOTSTRAP_BAT}}"'
-    cmds:
-      - cmd: 'git -C "{{.TASKFILE_DIR}}" submodule update --init --recursive'
-
-  vcpkg-integrate:
-    deps: [vcpkg-download]
-    internal: true
-    cmds:
-      - cmd: '{{.RUN}} "{{ fromSlash .VCPKG_EXE }}" integrate install'
-
-  vcpkg-download:
-    deps: [git-submodule-init]
-    status:
-      - 'test -f "{{.VCPKG_EXE}}"'
-    cmds:
-      - cmd: '{{.RUN}} "{{ fromSlash .VCPKG_BOOTSTRAP_BAT }}" -disableMetrics'
-
-  vcpkg:
-    deps: [vcpkg-download]
-    cmds:
-      - cmd: '{{.RUN}} "{{ fromSlash .VCPKG_EXE }}" {{.CLI_ARGS}}'
-
-  update-packages:
-    ignore_error: true
-    cmds:
-      - task: update-packages-pacman
-
-  update-packages-pacman:
-    deps: [pacman-unlock]
-    cmds:
-      - task: pacman-unlock
-      - cmd: 'pacman -Syu --noconfirm'
-        ignore_error: true
-
-  install-packages:
-    cmds:
-      - task: install-packages-scoop-pkg-config
-      - task: install-packages-pacman
-
-  install-packages-scoop-pkg-config:
-    deps: [scoop-install]
-    platforms: [windows]
-    status:
-      - pkg-config --version
-    cmds:
-      - cmd: |
-          scoop install \
-            extras/pkg-config-lite \
-            main/winflexbison
-
-  install-packages-pacman:
-    vars:
-      PACKAGES: '{{.MSYS2_PACKAGES | join " "}}'
-    cmds:
-      - task: pacman-unlock
-      - cmd: 'pacman -Syu --noconfirm'
-        ignore_error: true
-      - cmd: 'pacman -S --needed --noconfirm {{ .PACKAGES }}'
-        ignore_error: true
-      - task: pacman-unlock
-
-  install-each-package:
-    deps: [update-packages]
-    vars:
-      PACKAGES: '{{.MSYS2_PACKAGES | join " "}}'
-    cmds:
-      - for:
-          var: MSYS2_PACKAGES
-        task: install-package-pacman
+    install-packages-pacman:
         vars:
-          PACKAGE: '{{.ITEM}}'
+            PACKAGES: '{{.MSYS2_PACKAGES | join " "}}'
+        cmds:
+            - task: pacman-unlock
+            - cmd: "pacman -Syu --noconfirm"
+              ignore_error: true
+            - cmd: "pacman -S --needed --noconfirm {{ .PACKAGES }}"
+              ignore_error: true
+            - task: pacman-unlock
 
-  pacman-unlock:
-    status:
-      - 'test ! -f /var/lib/pacman/db.lck'
-    cmds:
-      - cmd: 'rm -f /var/lib/pacman/db.lck'
-        ignore_error: true
+    install-each-package:
+        deps: [update-packages]
+        vars:
+            PACKAGES: '{{.MSYS2_PACKAGES | join " "}}'
+        cmds:
+            - for:
+                  var: MSYS2_PACKAGES
+              task: install-package-pacman
+              vars:
+                  PACKAGE: "{{.ITEM}}"
 
-  install-package-pacman:
-    deps: [pacman-unlock]
-    requires:
-      vars: [PACKAGE]
-    desc: 'Install package {{.PACKAGE}}'
-    preconditions:
-      - 'pacman --version'
-    status:
-      - 'pacman -Qk {{.PACKAGE}}'
-    cmds:
-      - cmd: 'pacman -S --needed --noconfirm "{{.PACKAGE}}"'
+    pacman-unlock:
+        status:
+            - "test ! -f /var/lib/pacman/db.lck"
+        cmds:
+            - cmd: "rm -f /var/lib/pacman/db.lck"
+              ignore_error: true
 
-  delete:
-    internal: true
-    requires: { vars: [TARGET_DIR] }
-    status:
-      - 'test ! -d "{{.TARGET_DIR}}"'
-    cmds:
-      - cmd: '{{.RUN}} if exist "{{.TARGET_DIR}}" rmdir /s /q "{{.TARGET_DIR}}"'
-        platforms: [windows]
-      - cmd: '{{.RUN}} rm -rf "{{.TARGET_DIR}}"'
-        platforms: [linux, darwin]
+    install-package-pacman:
+        deps: [pacman-unlock]
+        requires:
+            vars: [PACKAGE]
+        desc: "Install package {{.PACKAGE}}"
+        preconditions:
+            - "pacman --version"
+        status:
+            - "pacman -Qk {{.PACKAGE}}"
+        cmds:
+            - cmd: 'pacman -S --needed --noconfirm "{{.PACKAGE}}"'
 
-  ninja:
-    deps: [meson]
-    preconditions:
-      - ninja --version
-    cmds:
-      - cmd: 'ninja -C "{{.BUILD_DIR}}"'
+    delete:
+        internal: true
+        requires: { vars: [TARGET_DIR] }
+        status:
+            - 'test ! -d "{{.TARGET_DIR}}"'
+        cmds:
+            - cmd: '{{.RUN}} if exist "{{.TARGET_DIR}}" rmdir /s /q "{{.TARGET_DIR}}"'
+              platforms: [windows]
+            - cmd: '{{.RUN}} rm -rf "{{.TARGET_DIR}}"'
+              platforms: [linux, darwin]
 
-  build-msbuild:
-    cmds:
-      - task: build-msbuild-gtk
-        vars: { CONFIG: Debug, PLATFORM: x64 }
-      - task: build-msbuild-gtk
-        vars: { CONFIG: Release, PLATFORM: x64 }
+    ninja:
+        deps: [meson]
+        preconditions:
+            - ninja --version
+        cmds:
+            - cmd: 'ninja -C "{{.BUILD_DIR}}"'
 
-  build-msbuild-gtk:
-    internal: true
-    deps: [install-dependencies]
-    vars:
-      CONFIG: '{{.CONFIG | default "Debug"}}'
-      PLATFORM: '{{.PLATFORM | default "x64"}}'
-    cmds:
-      - cmd: '"{{ .MSBUILD_EXE }}" "{{.TASKFILE_DIR}}/vs/gtk.sln" /t:Build /p:Configuration="{{.CONFIG}}" /p:Platform="{{.PLATFORM}}"'
+    build-msbuild:
+        cmds:
+            - task: build-msbuild-gtk
+              vars: { CONFIG: Debug, PLATFORM: x64 }
+            - task: build-msbuild-gtk
+              vars: { CONFIG: Release, PLATFORM: x64 }
 
-  sync:
-    sources:
-      - pyproject.toml
-    generates:
-      - .venv/**/*
-    cmds:
-      - cmd: rye sync --no-lock
+    build-msbuild-gtk:
+        internal: true
+        deps: [install-dependencies]
+        vars:
+            CONFIG: '{{.CONFIG | default "Debug"}}'
+            PLATFORM: '{{.PLATFORM | default "x64"}}'
+        cmds:
+            - cmd: '"{{ .MSBUILD_EXE }}" "{{.TASKFILE_DIR}}/vs/gtk.sln" /t:Build /p:Configuration="{{.CONFIG}}" /p:Platform="{{.PLATFORM}}"'
 
-  gtk-build:
-    deps: [sync, install-dependencies]
-    vars:
-      MESON_OPTIONS: >-
-        -Dgobject-introspection:werror=false
-        -Dgraphene:introspection=disabled
-        -Dintrospection=disabled
-        -Dmedia-gstreamer=disabled
-        -Dvulkan=disabled
-        --buildtype release
-        --wrap-mode nofallback
-        -D b_lto=true
-        -D strip=true
-        --default-library shared
-      CROSS_FILE_DEFAULT: /usr/share/mingw/toolchain-mingw64.meson
-      CROSS_FILE_WINE: /usr/share/mingw/toolchain-mingw64-wine.meson
-      MESON_EXE_WRAPPER_WINE: /usr/bin/x86_64-w64-mingw64-wine
-    cmds:
-      - cmd: |
-          . .gitlab-ci/show-info-linux.sh
-        ignore_error: true
-      - cmd: | # shell
-          set -eax
+    sync:
+        sources:
+            - pyproject.toml
+        generates:
+            - .venv/**/*
+        cmds:
+            - cmd: uv sync --no-lock
 
-          if [ -z "$CROSS_FILE" ]; then
-            if [ -z "$NEED_WINE" ]; then
-              export CROSS_FILE="{{.CROSS_FILE_DEFAULT}}"
-            else
-              export CROSS_FILE="{{.CROSS_FILE_WINE}}"
-              export MESON_EXE_WRAPPER="{{.MESON_EXE_WRAPPER_WINE}}"
-            fi
-          fi
+    gtk-build:
+        deps: [sync, install-dependencies]
+        vars:
+            MESON_OPTIONS: >-
+                -Dgobject-introspection:werror=false
+                -Dgraphene:introspection=disabled
+                -Dintrospection=disabled
+                -Dmedia-gstreamer=disabled
+                -Dvulkan=disabled
+                --buildtype release
+                --wrap-mode nofallback
+                -D b_lto=true
+                -D strip=true
+                --default-library shared
+            CROSS_FILE_DEFAULT: /usr/share/mingw/toolchain-mingw64.meson
+            CROSS_FILE_WINE: /usr/share/mingw/toolchain-mingw64-wine.meson
+            MESON_EXE_WRAPPER_WINE: /usr/bin/x86_64-w64-mingw64-wine
+        cmds:
+            - cmd: |
+                  . .gitlab-ci/show-info-linux.sh
+              ignore_error: true
+            - cmd: | # shell
+                  set -eax
 
-          rye run meson subprojects download
-          rye run meson subprojects update --reset
+                  if [ -z "$CROSS_FILE" ]; then
+                    if [ -z "$NEED_WINE" ]; then
+                      export CROSS_FILE="{{.CROSS_FILE_DEFAULT}}"
+                    else
+                      export CROSS_FILE="{{.CROSS_FILE_WINE}}"
+                      export MESON_EXE_WRAPPER="{{.MESON_EXE_WRAPPER_WINE}}"
+                    fi
+                  fi
 
-          if rye run meson setup {{.MESON_OPTIONS}} _build; then
-            echo "Meson configuration succeeded."
-          else
-            echo "Meson configuration failed, attempting to reconfigure."
-            if rye run meson setup --reconfigure {{.MESON_OPTIONS}} _build; then
-              echo "Meson reconfiguration succeeded."
-            else
-              echo "Meson reconfiguration failed."
-              exit 5
-            fi
-          fi
-          rye run meson compile -C _build
+                  uv run meson subprojects download
+                  uv run meson subprojects update --reset
+
+                  if uv run meson setup {{.MESON_OPTIONS}} _build; then
+                    echo "Meson configuration succeeded."
+                  else
+                    echo "Meson configuration failed, attempting to reconfigure."
+                    if uv run meson setup --reconfigure {{.MESON_OPTIONS}} _build; then
+                      echo "Meson reconfiguration succeeded."
+                    else
+                      echo "Meson reconfiguration failed."
+                      exit 5
+                    fi
+                  fi
+                  uv run meson compile -C _build
